name: Build, Tag and Push Docker Image to ECR
description: Apply updated container images to a running task
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  cluster_name:
    description: The destination name of the cluster to deploy to.
    required: true
  service_name:
    description: Name of the service.
    required: true
