name: Deploy latest Docker container image to ECS Service
description: Apply updated container images to an ECS service
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  environment_configuration:
    description: JSON object containing the AWS Account ID and ECS Cluster Name to Deploy to.
    required: true
  service_name:
    description: Name of the target service
    required: true
