name: Deploy latest Docker container image to ECS Service
description: Apply updated container images to an ECS service
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  cluster_name:
    description: The ECS cluster that contains the target service
    required: true
  service_name:
    description: Name of the target service
    required: true
